// -------------------------------------------------------------
// 
// File Name: /home/bonga/Desktop/EEE4022S/EEE4022S_Github/qaes/codegen/qft_3qubit/hdlsrc/qft_3qubit_fixpt_pkg.sv
// Created: 2024-10-26 09:25:26
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------



package qft_3qubit_fixpt_pkg;
  typedef  logic signed [13:0] vector_of_signed_logic_14;
  typedef  logic signed [14:0] vector_of_signed_logic_15;
  typedef  logic signed [17:0] vector_of_signed_logic_18;
  typedef  logic signed [18:0] vector_of_signed_logic_19;
  typedef  logic signed [27:0] vector_of_signed_logic_28;
  typedef  logic signed [31:0] vector_of_signed_logic_32;
endpackage: qft_3qubit_fixpt_pkg

