// -------------------------------------------------------------
// 
// File Name: /home/bonga/Desktop/EEE4022S/EEE4022S_Github/qaes/universal_q_gates/x_gate/codegen/x_gate/hdlsrc/x_gate_fixpt_pkg.sv
// Created: 2024-10-26 15:01:11
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------



package x_gate_fixpt_pkg;
  typedef  logic signed [63:0] vector_of_signed_logic_64;
  typedef  logic  [3:0] vector_of_unsigned_logic_4;
endpackage: x_gate_fixpt_pkg

